# Machine Learning 1 – TensorFlow Basics (Material 1/2)

This notebook follows the examples provided in the course material.
The goal is to understand how TensorFlow represents numerical data using tensors.


## Scalars, Vectors and Matrices

TensorFlow represents data as tensors.
- Scalar: single number (rank 0)
- Vector: list of numbers (rank 1)
- Matrix: table of numbers (rank 2)


In [7]:
import tensorflow as tf
import numpy as np

print("TF:", tf.__version__)

scalar = tf.constant(7)
vector = tf.constant([10, 20, 30])
matrix = tf.constant([[1., 2.], [3., 4.]])

print(scalar.shape, vector.shape, matrix.shape)


TF: 2.20.0
() (3,) (2, 2)


### Higher-dimensional tensors

Tensors can have more than two dimensions.
This is common in images and batches of data.


In [8]:
tensor = tf.constant([[[1],[2]], [[3],[4]]])
print(tensor.shape)


(2, 2, 1)


### Data types and casting

TensorFlow uses different data types.
Sometimes values must be converted for compatibility.


In [9]:
x = tf.constant([1.7, 7.4])
y = tf.constant([7, 10])

x16 = tf.cast(x, tf.float16)
y32 = tf.cast(y, tf.float32)


### Indexing and reshaping tensors

Tensor slicing is similar to NumPy.
Dimensions can be added or removed when needed.


In [10]:
rank2 = tf.constant([[10, 7], [3, 4]])
last_col = rank2[:, -1]

expanded = tf.expand_dims(rank2, -1)
squeezed = tf.squeeze(expanded, axis=-1)


### Matrix multiplication

Matrix multiplication is the core operation in neural networks.
The inner dimensions must match.


In [11]:
X = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float32)
Y = tf.constant([[7,8],[9,10],[11,12]], dtype=tf.float32)

result = tf.matmul(X, tf.transpose(Y))
print(result)


tf.Tensor(
[[ 23.  29.  35.]
 [ 53.  67.  81.]
 [ 83. 105. 127.]], shape=(3, 3), dtype=float32)


### Aggregation operations

Aggregation reduces tensors to summary values.


In [12]:
E = tf.constant(np.random.randint(0, 100, size=10))

print("min:", tf.reduce_min(E).numpy())
print("max:", tf.reduce_max(E).numpy())
print("mean:", tf.reduce_mean(tf.cast(E, tf.float32)).numpy())
print("sum:", tf.reduce_sum(E).numpy())


min: 8
max: 91
mean: 56.2
sum: 562
